name: Deploy STAGING release to GitHub Pages

on:
  push:
    branches:
      - staging
  workflow_dispatch: # optional manual trigger

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout staging branch
        uses: actions/checkout@v4

      - name: Deploy Staging
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: pages-staging     # staging deployment branch
          publish_dir: ./releases           # folder containing static files
          cname: staging.zampos-desktop.zamdahealth.com
